- target: 'https://username:password@hostname:9090/path?arg=value#anchor'
  scheme: 'https'
  host: 'hostname'
  port: 9090
  user: 'username'
  pass: 'password'
  path: '/path'
  query: 'arg=value'
  fragment: 'anchor'
